# -*- coding: utf-8 -*-
"""Generate 10jt.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1e_y7O_eoLd9vWmDpHDLO-bMw3dt9tmEI
"""

import random
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

row = 6
col = 9
table = (row,col)
matrix = np.zeros(table)
sum = 0
mat = []
n = 54
for i in range(n) :
  a = random.uniform(0,1)
  sum += a
  mat.append(a)
  
max = []
jml = 0
for i in range(n) :
  mat[i] = mat[i] / sum
  max.append(mat[i])
  
for i in range(n) :
  max[i] = max[i] * 1000
  jml += max[i]

i = 0    
a = 0
while (i < row) :
    j = 0
    while (j <col):
        matrix[i][j] = int(round(max[a])) * 10000
        j+=1
        a+=1
    i+=1

df = pd.DataFrame(matrix)
w = col + 5
h = row 
plt.figure(1, figsize=(w, h))
tb = plt.table(cellText=matrix, loc=(0,0), cellLoc='center')

tc = tb.properties()['child_artists']
for cell in tc: 
    cell.set_height(1.0/row)
    cell.set_width(1.0/col)
ax = plt.gca()
ax.set_xticks([])
ax.set_yticks([])
ax.title.set_text('Cara menabung 10 Juta dalam 1 Tahun')
ax.text(1.05, 1, 'Asumsi 1 kolom dilakukan untuk 1 minggu', style='italic',
        bbox={'facecolor': 'red', 'alpha': 0.5, 'pad': 10})
plt.show()